hide: yes
fields:
  meta_title:
    display: Page Meta Title
    instructions: "Enter the page title to display in search engine results (no more than 70 characters)"
    type: text
  meta_desc:
    display: Page Meta Description
    instructions: "Enter a short description to display in search engine results roughly 155 characters."
    type: text
  alt_title:
    display: Alternative Title
    instructions: "This will display as the first heading on the page, and can be more descriptive than the main title"
    type: text